name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build GFAse
      shell: bash -l {0}
      run: |
        mkdir build &&
        cd build &&
        cmake .. &&
        make
